package su.rocket.pytorch_test;

import java.util.HashMap;
import java.util.Map;

public class KinetikUtils {
    public static Map<Integer, String> map = new HashMap<>();
    static {
        map.put(1,"air drumming");
        map.put(2,"answering questions");
        map.put(4,"applying cream");
        map.put(6,"arm wrestling");
        map.put(7,"arranging flowers");
        map.put(8,"assembling computer");
        map.put(10,"baby waking up");
        map.put(11,"baking cookies");
        map.put(12,"balloon blowing");
        map.put(17,"bee keeping");
        map.put(18,"belly dancing");
        map.put(19,"bench pressing");
        map.put(20,"bending back");
        map.put(21,"bending metal");
        map.put(22,"biking through snow");
        map.put(23,"blasting sand");
        map.put(24,"blowing glass");
        map.put(25,"blowing leaves");
        map.put(26,"blowing nose");
        map.put(27,"blowing out candles");
        map.put(30,"bouncing on trampoline");
        map.put(32,"braiding hair");
        map.put(33,"breading or breadcrumbing");
        map.put(35,"brush painting");
        map.put(36,"brushing hair");
        map.put(37,"brushing teeth");
        map.put(38,"building cabinet");
        map.put(39,"building shed");
        map.put(40,"bungee jumping");
        map.put(42,"canoeing or kayaking");
        map.put(44,"carrying baby");
        map.put(46,"carving pumpkin");
        map.put(47,"catching fish");
        map.put(48,"catching or throwing baseball");
        map.put(49,"catching or throwing frisbee");
        map.put(50,"catching or throwing softball");
        map.put(52,"changing oil");
        map.put(53,"changing wheel");
        map.put(54,"checking tires");
        map.put(56,"chopping wood");
        map.put(58,"clay pottery making");
        map.put(59,"clean and jerk");
        map.put(60,"cleaning floor");
        map.put(61,"cleaning gutters");
        map.put(62,"cleaning pool");
        map.put(63,"cleaning shoes");
        map.put(64,"cleaning toilet");
        map.put(65,"cleaning windows");
        map.put(66,"climbing a rope");
        map.put(67,"climbing ladder");
        map.put(68,"climbing tree");
        map.put(69,"contact juggling");
        map.put(70,"cooking chicken");
        map.put(71,"cooking egg");
        map.put(72,"cooking on campfire");
        map.put(73,"cooking sausages");
        map.put(74,"counting money");
        map.put(75,"country line dancing");
        map.put(76,"cracking neck");
        map.put(77,"crawling baby");
        map.put(78,"crossing river");
        map.put(80,"curling hair");
        map.put(81,"cutting nails");
        map.put(82,"cutting pineapple");
        map.put(83,"cutting watermelon");
        map.put(84,"dancing ballet");
        map.put(85,"dancing charleston");
        map.put(86,"dancing gangnam style");
        map.put(87,"dancing macarena");
        map.put(89,"decorating the christmas tree");
        map.put(92,"disc golfing");
        map.put(93,"diving cliff");
        map.put(95,"doing aerobics");
        map.put(96,"doing laundry");
        map.put(97,"doing nails");
        map.put(99,"dribbling basketball");
        map.put(101,"drinking beer");
        map.put(102,"drinking shots");
        map.put(103,"driving car");
        map.put(104,"driving tractor");
        map.put(105,"drop kicking");
        map.put(106,"drumming fingers");
        map.put(107,"dunking basketball");
        map.put(108,"dying hair");
        map.put(109,"eating burger");
        map.put(110,"eating cake");
        map.put(111,"eating carrots");
        map.put(112,"eating chips");
        map.put(113,"eating doughnuts");
        map.put(114,"eating hotdog");
        map.put(115,"eating ice cream");
        map.put(116,"eating spaghetti");
        map.put(117,"eating watermelon");
        map.put(118,"egg hunting");
        map.put(119,"exercising arm");
        map.put(120,"exercising with an exercise ball");
        map.put(121,"extinguishing fire");
        map.put(123,"feeding birds");
        map.put(124,"feeding fish");
        map.put(125,"feeding goats");
        map.put(126,"filling eyebrows");
        map.put(127,"finger snapping");
        map.put(128,"fixing hair");
        map.put(129,"flipping pancake");
        map.put(130,"flying kite");
        map.put(131,"folding clothes");
        map.put(132,"folding napkins");
        map.put(133,"folding paper");
        map.put(134,"front raises");
        map.put(135,"frying vegetables");
        map.put(136,"garbage collecting");
        map.put(138,"getting a haircut");
        map.put(139,"getting a tattoo");
        map.put(140,"giving or receiving award");
        map.put(141,"golf chipping");
        map.put(142,"golf driving");
        map.put(143,"golf putting");
        map.put(144,"grinding meat");
        map.put(145,"grooming dog");
        map.put(146,"grooming horse");
        map.put(147,"gymnastics tumbling");
        map.put(148,"hammer throw");
        map.put(151,"high jump");
        map.put(152,"high kick");
        map.put(153,"hitting baseball");
        map.put(154,"hockey stop");
        map.put(155,"holding snake");
        map.put(159,"hula hooping");
        map.put(161,"hurling (sport)");
        map.put(162,"ice climbing");
        map.put(163,"ice fishing");
        map.put(164,"ice skating");
        map.put(166,"javelin throw");
        map.put(169,"juggling balls");
        map.put(170,"juggling fire");
        map.put(171,"juggling soccer ball");
        map.put(172,"jumping into pool");
        map.put(173,"jumpstyle dancing");
        map.put(174,"kicking field goal");
        map.put(175,"kicking soccer ball");
        map.put(181,"laying bricks");
        map.put(182,"long jump");
        map.put(184,"making a cake");
        map.put(185,"making a sandwich");
        map.put(186,"making bed");
        map.put(187,"making jewelry");
        map.put(188,"making pizza");
        map.put(189,"making snowman");
        map.put(190,"making sushi");
        map.put(191,"making tea");
        map.put(193,"massaging back");
        map.put(194,"massaging feet");
        map.put(195,"massaging legs");
        map.put(196,"massaging person's head");
        map.put(197,"milking cow");
        map.put(198,"mopping floor");
        map.put(200,"moving furniture");
        map.put(201,"mowing lawn");
        map.put(202,"news anchoring");
        map.put(203,"opening bottle");
        map.put(204,"opening present");
        map.put(208,"passing American football (in game)");
        map.put(209,"passing American football (not in game)");
        map.put(210,"peeling apples");
        map.put(211,"peeling potatoes");
        map.put(212,"petting animal (not cat)");
        map.put(213,"petting cat");
        map.put(214,"picking fruit");
        map.put(215,"planting trees");
        map.put(217,"playing accordion");
        map.put(218,"playing badminton");
        map.put(219,"playing bagpipes");
        map.put(220,"playing basketball");
        map.put(221,"playing bass guitar");
        map.put(222,"playing cards");
        map.put(223,"playing cello");
        map.put(224,"playing chess");
        map.put(225,"playing clarinet");
        map.put(226,"playing controller");
        map.put(227,"playing cricket");
        map.put(228,"playing cymbals");
        map.put(229,"playing didgeridoo");
        map.put(230,"playing drums");
        map.put(231,"playing flute");
        map.put(232,"playing guitar");
        map.put(233,"playing harmonica");
        map.put(234,"playing harp");
        map.put(235,"playing ice hockey");
        map.put(236,"playing keyboard");
        map.put(237,"playing kickball");
        map.put(238,"playing monopoly");
        map.put(239,"playing organ");
        map.put(240,"playing paintball");
        map.put(241,"playing piano");
        map.put(242,"playing poker");
        map.put(243,"playing recorder");
        map.put(244,"playing saxophone");
        map.put(245,"playing squash or racquetball");
        map.put(246,"playing tennis");
        map.put(247,"playing trombone");
        map.put(248,"playing trumpet");
        map.put(249,"playing ukulele");
        map.put(250,"playing violin");
        map.put(251,"playing volleyball");
        map.put(252,"playing xylophone");
        map.put(253,"pole vault");
        map.put(254,"presenting weather forecast");
        map.put(255,"pull ups");
        map.put(256,"pumping fist");
        map.put(257,"pumping gas");
        map.put(258,"punching bag");
        map.put(259,"punching person (boxing)");
        map.put(260,"push up");
        map.put(261,"pushing car");
        map.put(262,"pushing cart");
        map.put(263,"pushing wheelchair");
        map.put(264,"reading book");
        map.put(265,"reading newspaper");
        map.put(266,"recording music");
        map.put(267,"riding a bike");
        map.put(268,"riding camel");
        map.put(269,"riding elephant");
        map.put(270,"riding mechanical bull");
        map.put(271,"riding mountain bike");
        map.put(272,"riding mule");
        map.put(273,"riding or walking with horse");
        map.put(274,"riding scooter");
        map.put(275,"riding unicycle");
        map.put(276,"ripping paper");
        map.put(277,"robot dancing");
        map.put(278,"rock climbing");
        map.put(279,"rock scissors paper");
        map.put(280,"roller skating");
        map.put(281,"running on treadmill");
        map.put(283,"salsa dancing");
        map.put(284,"sanding floor");
        map.put(285,"scrambling eggs");
        map.put(286,"scuba diving");
        map.put(287,"setting table");
        map.put(288,"shaking hands");
        map.put(289,"shaking head");
        map.put(290,"sharpening knives");
        map.put(291,"sharpening pencil");
        map.put(292,"shaving head");
        map.put(293,"shaving legs");
        map.put(294,"shearing sheep");
        map.put(295,"shining shoes");
        map.put(296,"shooting basketball");
        map.put(297,"shooting goal (soccer)");
        map.put(298,"shot put");
        map.put(299,"shoveling snow");
        map.put(300,"shredding paper");
        map.put(301,"shuffling cards");
        map.put(302,"side kick");
        map.put(303,"sign language interpreting");
        map.put(307,"ski jumping");
        map.put(308,"skiing (not slalom or crosscountry)");
        map.put(309,"skiing crosscountry");
        map.put(310,"skiing slalom");
        map.put(311,"skipping rope");
        map.put(315,"sled dog racing");
        map.put(317,"smoking hookah");
        map.put(318,"snatch weight lifting");
        map.put(326,"spinning poi");
        map.put(327,"spray painting");
        map.put(329,"springboard diving");
        map.put(331,"sticking tongue out");
        map.put(332,"stomping grapes");
        map.put(333,"stretching arm");
        map.put(334,"stretching leg");
        map.put(335,"strumming guitar");
        map.put(336,"surfing crowd");
        map.put(337,"surfing water");
        map.put(338,"sweeping floor");
        map.put(339,"swimming backstroke");
        map.put(340,"swimming breast stroke");
        map.put(341,"swimming butterfly stroke");
        map.put(342,"swing dancing");
        map.put(343,"swinging legs");
        map.put(344,"swinging on something");
        map.put(345,"sword fighting");
        map.put(346,"tai chi");
        map.put(347,"taking a shower");
        map.put(348,"tango dancing");
        map.put(349,"tap dancing");
        map.put(350,"tapping guitar");
        map.put(351,"tapping pen");
        map.put(352,"tasting beer");
        map.put(353,"tasting food");
        map.put(356,"throwing axe");
        map.put(357,"throwing ball");
        map.put(358,"throwing discus");
        map.put(361,"tossing coin");
        map.put(362,"tossing salad");
        map.put(363,"training dog");
        map.put(365,"trimming or shaving beard");
        map.put(366,"trimming trees");
        map.put(367,"triple jump");
        map.put(368,"tying bow tie");
        map.put(369,"tying knot (not on a tie)");
        map.put(370,"tying tie");
        map.put(372,"unloading truck");
        map.put(373,"using computer");
        map.put(374,"using remote controller (not gaming)");
        map.put(375,"using segway");
        map.put(377,"waiting in line");
        map.put(378,"walking the dog");
        map.put(379,"washing dishes");
        map.put(380,"washing feet");
        map.put(381,"washing hair");
        map.put(382,"washing hands");
        map.put(383,"water skiing");
        map.put(384,"water sliding");
        map.put(385,"watering plants");
        map.put(386,"waxing back");
        map.put(387,"waxing chest");
        map.put(388,"waxing eyebrows");
        map.put(389,"waxing legs");
        map.put(390,"weaving basket");
        map.put(394,"wrapping present");
        map.put(0,"abseiling");
        map.put(3,"applauding");
        map.put(5,"archery");
        map.put(9,"auctioning");
        map.put(13,"bandaging");
        map.put(14,"barbequing");
        map.put(15,"bartending");
        map.put(16,"beatboxing");
        map.put(28,"bobsledding");
        map.put(29,"bookbinding");
        map.put(31,"bowling");
        map.put(34,"breakdancing");
        map.put(41,"busking");
        map.put(43,"capoeira");
        map.put(45,"cartwheeling");
        map.put(51,"celebrating");
        map.put(55,"cheerleading");
        map.put(57,"clapping");
        map.put(79,"crying");
        map.put(88,"deadlifting");
        map.put(90,"digging");
        map.put(91,"dining");
        map.put(94,"dodgeball");
        map.put(98,"drawing");
        map.put(100,"drinking");
        map.put(122,"faceplanting");
        map.put(137,"gargling");
        map.put(149,"headbanging");
        map.put(150,"headbutting");
        map.put(156,"hopscotch");
        map.put(157,"hoverboarding");
        map.put(158,"hugging");
        map.put(160,"hurdling");
        map.put(165,"ironing");
        map.put(167,"jetskiing");
        map.put(168,"jogging");
        map.put(176,"kissing");
        map.put(177,"kitesurfing");
        map.put(178,"knitting");
        map.put(179,"krumping");
        map.put(180,"laughing");
        map.put(183,"lunge");
        map.put(192,"marching");
        map.put(199,"motorcycling");
        map.put(205,"paragliding");
        map.put(206,"parasailing");
        map.put(207,"parkour");
        map.put(216,"plastering");
        map.put(282,"sailing");
        map.put(304,"singing");
        map.put(305,"situp");
        map.put(306,"skateboarding");
        map.put(312,"skydiving");
        map.put(313,"slacklining");
        map.put(314,"slapping");
        map.put(316,"smoking");
        map.put(319,"sneezing");
        map.put(320,"sniffing");
        map.put(321,"snorkeling");
        map.put(322,"snowboarding");
        map.put(323,"snowkiting");
        map.put(324,"snowmobiling");
        map.put(325,"somersaulting");
        map.put(328,"spraying");
        map.put(330,"squat");
        map.put(354,"testifying");
        map.put(355,"texting");
        map.put(359,"tickling");
        map.put(360,"tobogganing");
        map.put(364,"trapezing");
        map.put(371,"unboxing");
        map.put(376,"vault");
        map.put(391,"welding");
        map.put(392,"whistling");
        map.put(393,"windsurfing");
        map.put(395,"wrestling");
        map.put(396,"writing");
        map.put(397,"yawning");
        map.put(398,"yoga");
        map.put(399,"zumba");
    }
}
